import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";


import { Nunito } from 'next/font/google';

const nunito = Nunito({
    subsets: ["latin", "vietnamese"],
  // subsets: ['latin'],   // Chọn subset phù hợp, ví dụ latin hoặc vietnamese
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'], // Chọn weight cần dùng
  display: 'swap',      // Tối ưu hiển thị text
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function CmsLayout({ children }: { children: React.ReactNode }) {
  const token = (await cookies()).get("accessToken")?.value;

  const currentPath = "/" + (globalThis as any).__NEXT_ROUTER__?.currentPath || "";

  // console.log(currentPath);
  // // Tránh redirect loop tại login
  // if (!token && currentPath !== "/cms/login") {
  //   console.log(0);
  //   redirect("/cms/login");
  // }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${nunito.className}`}
      >
        {children}
      </body>
    </html>
  );
}
