import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const token = (await cookies()).get('accessToken')?.value;

//   if (!token) {
//     redirect('/cms/login');
//   }

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




export default async function CmsLayout({ children }: { children: React.ReactNode }) {
  const token = (await cookies()).get("accessToken")?.value;

  const currentPath = "/" + (globalThis as any).__NEXT_ROUTER__?.currentPath || "";

  // Tránh redirect loop tại login
  if (!token && currentPath !== "/cms/login") {
    redirect("/cms/login");
  }

  // return (
  //   <div>
  //     {children}
  //   </div>
  // );



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
